# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on tag events but only for the main branch
  push:
    tags:
      - "V*.*.*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker pull marklion/zh_deploy:v1.0
          docker run   -v `realpath .`:`realpath .` marklion/zh_deploy:v1.0  make -j -f `realpath .`/Makefile VERSION_TAG=$GITHUB_REF_NAME
      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            ./build/install.sh